<!-- carousel works-->
<section class="slice">

    <div class="container">
        <div class="row">
        
            <div class="span12">
                <h2><span>Featured </span>works</h2>
                <div class="divider"><span></span></div>  
            </div>
            <div class="span12">

                <div id="projectCarousel" class="carousel slide">

                    <div class="carousel-inner da-thumbs">

                        <div class="active item">
                            <div class="row">
                                <div  class="span3" >
                                    <article>

                                        <a href="images/works/work1-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work1.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 1</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>

                                    </article> </div>
                                <div  class="span3">
                                    <article>

                                        <a href="images/works/work8-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work8.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 2</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article> 
                                </div>
                                <div  class="span3">   


                                    <article>

                                        <a href="images/works/work3-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work3.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 3</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article>    
                                </div><div  class="span3" >
                                    <article>

                                        <a href="images/works/work2-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work2.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 4</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article> 
                                </div>

                            </div>
                        </div>


                        <div class="item">
                            <div class="row">


                                <div  class="span3" >
                                    <article>

                                        <a href="images/works/work4-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work4.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 5</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article> 


                                </div><div  class="span3" >
                                    <article>

                                        <a href="images/works/work5-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work5.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 6</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article> 

                                </div><div  class="span3" >
                                    <article>

                                        <a href="images/works/work6-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work6.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 7</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article>                                


                                </div><div  class="span3" >
                                    <article>

                                        <a href="images/works/work7-big.jpg" class="prettyPhoto">
                                            <section>
                                                <img alt="" src="images/works/work7.jpg" />
                                            </section>
                                            <div>
                                                <span class="iconWrapper iconLink"><i class="icon-search"></i></span> 
                                            </div>
                                        </a>
                                        <section class="projectInfo"><h3>Project 8</h3><p>Aspice, officio fungeris sine spe honoris amplioris</p></section>
                                    </article> 
                                </div>

                            </div>
                        </div>




                    </div>
                    <a class="left carousel-control" href="#projectCarousel" data-slide="prev"><i class="icon-left-circle"></i></a>
                    <a class="right carousel-control" href="#projectCarousel" data-slide="next"><i class="icon-right-circle"></i></a>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- carousel works-->