<div id="footer">
    <div class="container">
        <p>
            <a href="#"><span class="label label-success"><i class="icon-user"></i>Администратор</span></a>
            | <i class="icon-calendar"></i> Sept 16th, 2012 at 4:20 pm
            | <i class="icon-comment"></i>3 Ответа
            | <i class="icon-share"></i>39 Сообщений
            | <span class="pull-right">Powered by ZF <?php echo \Zend\Version\Version::VERSION ?>&nbsp;
            <i class="icon-info-sign"></i><?php echo $this->title ?> 2012 &copy;
            </span>

        </p>
        
    </div>
</div>