<ul class="menu fading l_tinynav1">
    <?php
    $output = '';
    foreach ($this->container as $page) {
        switch($page->id){
            case 'login':
                $output .= '<li><a href="#loginModal" role="button" data-toggle="modal"><i class="icon-briefcase"></i>' . $page->getLabel() . '</a></li>';                
            break;         
            case 'home':
                $output .= '<li><a href="' . $page->getHref() . '" class="' . $page->getClass() . '"><i class="icon-home"></i>' . $page->getLabel() . '</a></li>';                
            break;         
            case 'desk':
                $output .= '<li><a href="' . $page->getHref() . '" class="' . $page->getClass() . '"><i class="icon-th-list"></i>' . $page->getLabel() . '</a></li>';                
            break;         
            case 'reply':
                $output .= '<li><a href="' . $page->getHref() . '" class="' . $page->getClass() . '"><i class="icon-comment"></i>' . $page->getLabel() . '</a></li>';                
            break;         
            case 'users':
                $output .= '<li><a href="' . $page->getHref() . '" class="' . $page->getClass() . '"><i class="icon-user"></i>' . $page->getLabel() . '</a></li>';                
            break;         
            case 'news':
                $output .= '<li><a href="' . $page->getHref() . '" class="' . $page->getClass() . '"><i class="icon-globe"></i>' . $page->getLabel() . '</a>';                
                $output .= '<ul><li><a>test</a></li></ul></li>';
            break;         
        }
    }
    echo $output;
    ?>
</ul>
