<!-- header -->
<header id="mainHeader" class="clearfix">


    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">

                <a href="index.html" class="brand"><img src="images/main-logo.png" alt="Ohmy website template"/></a>


                <nav id="mainMenu" class="clearfix">
                    <ul>
                        <li><a href="index.html" class="firstLevel active" >Home</a>
                            <ul>
                                <li><a href="index.html">Revolution Slider 1</a></li>
                                <li><a href="home1.html">Revolution Slider 2</a></li>
                                <li><a href="home2.html">Camera Slider</a></li>
                                <li><a href="home3.html">Flexi Slider</a></li>
                                <li><a href="home4.html">No Slider Video</a></li>
                                <li><a href="home5.html">No Slider Portfolio</a></li>
                                <li><a href="home6.html" class="last">No Slider</a></li>
                            </ul>
                        </li>
                        <li>
                        <li><a href="#" class="firstLevel">Colors</a>
                            <ul>
                                <li><a href="#" class="hasSubMenu">Light background</a>
                                    <ul class="switcher">
                                        <li><a href="css/orange.css">Orange</a></li>
                                        <li><a href="css/yellow.css">Yellow</a></li>
                                        <li><a href="css/sea-green.css">Sea green</a></li>
                                        <li><a href="css/green.css">Green</a></li>
                                        <li><a href="css/blue.css">Dark blue</a></li>
                                        <li><a href="css/light.css">Light blue</a></li>
                                        <li><a href="css/pink.css">Pink</a></li>
                                        <li><a href="css/coffee.css">Coffee</a></li>
                                        <li><a href="css/red.css">Red</a></li>
                                        <li><a href="css/black-white.css">Black & white</a></li>
                                    </ul>
                                </li>
                                <li><a href="#" class="hasSubMenu last">Dark background</a>
                                    <ul class="switcher">
                                        <li><a href="css/dark-orange.css">Dark Orange</a></li>
                                        <li><a href="css/dark-yellow.css">Dark Yellow</a></li>
                                        <li><a href="css/dark-sea-green.css">Dark Sea green</a></li>
                                        <li><a href="css/dark-green.css">Dark Green</a></li>
                                        <li><a href="css/dark-blue.css">Dark Dark blue</a></li>
                                        <li><a href="css/dark-light.css">Dark Light blue</a></li>
                                        <li><a href="css/dark-pink.css">Dark Pink</a></li>
                                        <li><a href="css/dark-coffee.css">Dark Coffee</a></li>
                                        <li><a href="css/dark-red.css">Dark Red</a></li>
                                        <li><a href="css/dark-black-white.css" class="last">Dark Black & white</a></li>
                                    </ul>   
                                </li>
                            </ul>
                        </li>


                        <li><a href="template-features.html" class="firstLevel">Features</a></li>


                        <li><a href="template-columns.html" class="firstLevel">Templates</a>
                            <ul >
                                <li><a href="template-columns.html">Columns</a></li>
                                <li><a href="template-typography.html">Typography</a></li>
                                <li><a href="template-sidebar.html">Sidebar</a></li>
                                <li><a href="template-about.html">About us</a></li>
                                <li><a href="template-services.html">Services</a></li>
                                <li><a href="template-faq.html">FAQ</a></li>
                                <li><a href="template-404.html">404 error</a></li>
                                <li><a href="template-our-team.html">Our team</a></li>
                                <li><a href="template-pricing.html">Pricing table</a></li>
                                <li><a href="template-full-width.html">Full width</a></li>
                                <li><a href="#" class="hasSubMenu last">Sub menu</a>
                                    <ul>
                                        <li><a href="#" class="">Third level 1</a></li>
                                        <li><a href="#" class="">Third level 2</a></li>
                                        <li><a href="#" class="">Third level 3</a></li>
                                        <li>
                                            <a href="#" class="hasSubMenu last">Third level 4</a>
                                            <ul>
                                                <li><a href="#" class="">Fourth level 1</a></li>
                                                <li><a href="#" class="">Fourth level 2</a></li>
                                                <li><a href="#" class="last">Fourth level 3</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="portfolio-vertical.html" class="firstLevel">Portfolio</a>
                            <ul>
                                <li><a href="portfolio-vertical.html">Vertical</a></li>
                                <li><a href="portfolio-masonery.html">Masonery</a></li>
                                <li><a href="portfolio-2columns.html">2 columns</a></li>
                                <li><a href="portfolio-3columns.html">3 columns</a></li>
                                <li><a href="portfolio-4columns.html">4 columns</a></li>
                                <li><a href="portfolio-project.html" class="last">Single project</a></li>
                            </ul>
                        </li>
                        <li><a href="blog-home.html" class="firstLevel">Blog</a>
                            <ul>
                                <li><a href="blog-home.html">Homepage</a></li>
                                <li><a href="blog-post.html" class="last">Post</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="template-contact.html" class="firstLevel last">Contact</a>
                            <ul>
                                <li><a href="template-contact.html" class="last">Contact template 1</a></li>
                                <li><a href="template-contact-2.html" class="last">Contact template 2</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>

            </div>
        </div>
    </div>
</header>
<!-- header --> 