            <header>
                <!-- Top Bar -->
                <div class="top-bar">
                    <div class="container">
                        <div class="row">
                            <div class="span7 hidden-phone">
                                <!-- Menu Top -->
                                <ul class="menu-top unstyled inline">
                                    <li><a href="mailto:cawa123@mail.ru">cawa123@mail.ru</a></li>
                                </ul>
                                <!-- End Menu Top -->
                            </div>
                            <div class="span5">
                                <!-- Access -->
                                <ul class="access unstyled">
                                    <li class="register">Not have account? <a href="login.html">Sign Up</a></li>
                                    <li class="login-area"><a href="#"><i class="icon-user"></i> Login</a>
                                        <div class="form">
                                            <form action="<?php echo  $this->url('caUser', array('action' => 'login')); ?>" method="POST">
                                                <div class="control-group">
                                                    <label class="control-label" for="inputE-mail">E-mail</label>
                                                    <div class="controls">
                                                        <div class="input-prepend">
                                                            <span class="add-on"><i class="icon-envelope"></i></span>
                                                            <input class="input-medium" type="text" id="inputE-mail" placeholder="Email address">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="control-group">
                                                    <label class="control-label" for="inputPassword">Password</label>
                                                    <div class="controls">
                                                        <div class="input-prepend">
                                                            <span class="add-on"><i class="icon-key"></i></span>
                                                            <input class="input-medium" type="password" id="inputPassword" placeholder="Password">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="control-group">
                                                    <div class="controls">
                                                        <label class="checkbox">
                                                            <input type="checkbox"> Remember me
                                                        </label>
                                                        <div class="pull-left">
                                                            <a href="#" class="link"><i class="icon-exclamation-sign"></i> Lost password?</a>
                                                        </div>
                                                        <div class="pull-right">
                                                            <button type="submit" class="btn">Sign in</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </li>
                                </ul>
                                <!-- End Access -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Top Bar -->
                <!-- Header -->
                <div class="header">
                    <div class="container">
                        <div class="row">
                            <div class="span4">
                                <!-- Logo -->
                                <div class="logo">
                                    <a href="index-2.html"><img id="logo" src="/img/logo_bp.ng" alt="City Nightlife"></a>
                                    <h2 class="hide-text">City Nightlife - Entertainment, Cities Guide and Promotions</h2>
                                </div>
                                <!-- End Logo -->
                            </div>
                            <div class="span8">
                                <div class="pull-right">
                                    <!-- Ad-728 -->
                                    <div class="ad-728 hidden-phone">
                                        <div class="/image">
                                            <a href="#"><img id="ad-728" src="/images/banners/728x90_default.png" alt="Advertising" /></a>
                                        </div>
                                        <div class="advertising"></div>
                                    </div>
                                    <!-- End Ad-728 -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Header -->
                <!-- Navigation -->
                <nav class="navigation lsteel-blue" id="nav">
                    <div class="container">
                        <div class="row">
                            <div class="span12">
                            <?php
                                $this->navigation('Navigation')->menu()->setPartial('partials/headerMenu');
                                echo $this->navigation('Navigation')->menu()->render();
                                ?>   
                               
                           
                                <div class="pull-right">
								<div id="language" class="language visible-desktop">
									<a href="#" class="current"><i class="icon-globe"></i> <span>English</span> <i class="icon-angle-down"></i></a>
									<div class="language-selector">
										<div class="page-header">
											<h5><i class="icon-globe"></i> Select your language <span class="pull-right"><a href="#" class="close"><i class="icon-remove-sign"></i></a></span></h5>
										</div>
											<li class="select"><a href="#" data-language="English"><img src="/images/flags/us.png" alt=""> English</a></li>
											<li><a href="#" data-language="Espanol"><img src="/images/flags/es.png" alt=""> Espanol</a></li>
											<li><a href="#" data-language="???????"><img src="/images/flags/sa.png" alt=""> ???????</a></li>
											<li><a href="#" data-language="Deutsch"><img src="/images/flags/de.png" alt=""> Deutsch</a></li>
											<li><a href="#" data-language="Nederlands"><img src="/images/flags/lu.png" alt=""> Nederlands</a></li>
											<li><a href="#" data-language="Italiano"><img src="/images/flags/ie.png" alt=""> Italiano</a></li>
											<li><a href="#" data-language="Portugues"><img src="/images/flags/br.png" alt=""> Portugues</a></li>
											<li><a href="#" data-language="Bahasa"><img src="/images/flags/lr.png" alt=""> Bahasa</a></li>
											<li><a href="#" data-language="Turkce"><img src="/images/flags/tr.png" alt=""> Turkce</a></li>
											<li><a href="#" data-language="????"><img src="/images/flags/cn.png" alt=""> ????</a></li>
											<li><a href="#" data-language="Francais"><img src="/images/flags/gf.png" alt=""> Francais</a></li>
											<li><a href="#" data-language="???"><img src="/images/flags/jp.png" alt=""> ???</a></li>
										<hr>
										<p><a href="#">Help translate City Nightlife into your language</a></p>
									</div>
							
								</div>
							</div>
                                <!-- <div class="pull-right">
                                        <div class="language hidden-phone">
                                                <ul class="lang-inline">
                                                        <li class="lang-active">
                                                                <a href="#"><img src="/images/en.png" alt="" data-toggle="tooltip" title="English" /></a>
                                                        </li>
                                                        <li>
                                                                <a href="#"><img src="/images/es.png" alt="" data-toggle="tooltip" title="Espanol" /></a>
                                                        </li>
                                                        <li>
                                                                <a href="#"><img src="/images/br.png" alt="" data-toggle="tooltip" title="Portugues" /></a>
                                                        </li>
                                                </ul>
                                        </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </nav>
                <!-- End Navigation -->
                 <?php if($this->controllerName()=='Application\Controller\Index'){ echo $this->partial('partials/slider');} ?>
                <!-- Search -->
                <div class="search">
                    <div class="container">
                        <div class="row">
                            <div class="span6">
                                <!-- Breadcrumb -->
                                <?php
                                $this->navigation('Navigation')->menu()->setPartial('partials/breadcrumbs');
                                echo $this->navigation('Navigation')->menu()->render();
                                ?>   
                                <!-- End Breadcrumb -->
                            </div>
                            <div class="span6">
                                <div class="pull-right">
                                    <!-- Search -->
                                    <form action="http://themes.atomtech.com.br/" method="post" class="form-inline">
                                        <div class="input-append">
                                            <input name="searchword" maxlength="20" class="inputbox input-xlarge" type="text" size="20" value="" placeholder="What are you looking for?" />
                                            <button class="btn" data-toggle="tooltip" title="Random Search"><i class="icon-random"></i></button>
                                            <button class="btn" data-toggle="tooltip" title="Advanced Search"><i class="icon-tasks"></i></button>
                                            <button class="btn"><i class="icon-search"></i> <span class="hidden-phone">Search</span></button>
                                        </div>
                                    </form>
                                    <!-- End Search -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Search -->
            </header>
