<div id="headerTopBar">
	<div class="inner">
		<p class="contactInfo"><a href="mailto:info@yourcompany.com" class="contactEmail" data-icon="&#x41;">info@yourcompany.com</a>/<span class="contactTel" data-icon="&#x40;">+48 555-654-983</span></p>
		<p class="sloganText visible-desktop">Welcome to Crafty, a powerful, responsive and retina-ready Site Template!</p>
		
		<ul class="socialButtons">
			<li class="tw"><a href="#" target="_blank" data-icon="&#xe095;"></a></li>
			<li class="fb"><a href="#" target="_blank" data-icon="&#xe091;"></a></li>
			<li class="dri"><a href="#" target="_blank" data-icon="&#xe0a4;"></a></li>
			<li class="for"><a href="#" target="_blank" data-icon="&#xe0a7;"></a></li>
			<li class="sc"><a href="#" target="_blank" data-icon="&#xe0c1;"></a></li>
			<li class="gp"><a href="#" target="_blank" data-icon="&#xe08d;"></a></li>
			
		</ul>
		<div class="clearfix"></div>
		
	</div>
</div>