<nav id="main_menu">
    <div class="menu_wrap">
        <ul class="nav sf-menu">
            <li class="current"><a href="/">Home</a></li>
            <li><a href="/application/index/about">About</a></li>
            <li class="sub-menu"><a href="javascript:{}">Features</a>
                <ul>
                    <li><a href="scaffolding.html"><span>-</span>Scaffolding</a></li>
                    <li><a href="typography.html"><span>-</span>Typography</a></li>
                    <li><a href="shortcodes.html"><span>-</span>Shortcodes</a></li>
                    <li><a href="tables.html"><span>-</span>Tables</a></li>                                          
                </ul>                                          
            </li>
            <li class="sub-menu"><a href="javascript:{}">Portfolio</a>
                <ul>
                    <li><a href="portfolio_2columns.html"><span>-</span>2 Columns</a></li>
                    <li><a href="portfolio_3columns.html"><span>-</span>3 Columns</a></li>
                    <li><a href="portfolio_4columns.html"><span>-</span>4 Columns</a></li>                                      
                </ul>
            </li>                                  
            <li class="sub-menu"><a href="javascript:{}">Blog</a>
                <ul>
                    <li><a href="/application/index/blog"><span>-</span>Blog with right sidebar</a></li>
                    <li><a href="blog_post.html"><span>-</span>Blog post</a></li>                                      
                </ul>
            </li>
            <li><a href="contacts.html">Contacts</a></li>
        </ul>
    </div>
</nav>                