<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a href="<?php
            echo $this->url('application');
            ?>" class="brand"><img src="/img/logo.png" alt="Travel Around"/></a>
            <?php
            $output = '<nav id="mainMenu" class="clearfix">';
            $output .= ' <ul>';
            foreach ($this->container as $page) {
                if ($page->id == 'login') {
                    $output .='<li>';
                    $output .= '<a href="#loginModal" role="button" data-toggle="modal"><i class="icon-briefcase"></i>' . $page->getLabel() . '</a>';
                    $output .='</li>';
                    //}
                } else {
                    $output .= '<li>';
                    $output .= '<a href="' . $page->getHref() . '" class="' . $page->getClass() . '" >';
                    switch ($page->id) {
                        case 'home': {
                            $output .= '<i class="icon-home"></i>';
                            break;
                        }

                        case 'desk': {
                            $output .= '<i class="icon-th-list"></i>';
                            break;
                        }
                        case 'reply': {
                            $output .= '<i class="icon-comment"></i>';
                            break;
                        }
                        case 'users': {
                            $output .= '<i class="icon-user"></i>';
                            break;
                        }
                        case 'news': {
                            $output .= '<i class="icon-globe"></i>';
                            break;
                        }
                    }
                    $output .=$page->getLabel();
                    $output .='</a>';
                    $output .='</li>';
                    $output .= '<li class="divider-vertical"></li>';
                }
            }
            ?>
            <form accept-charset="UTF-8" action="" method="POST" class="navbar-form form-search pull-right" id="navBarSearch">
                <div class="input-append">
                    <input type="text" placeholder="Search" class="span2 search-query" name="q">
                    <button class="btn" type="submit">Search</button>
                </div>
            </form>
            <?php
            $output .= '</li></ul></nav>';

            echo $output;
            //echo $this->userInfoHelper();
            ?>

        </div>
    </div>
</div>

<div id="loginModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Login to MyWebsite.com</h3>

    </div>
    <div class="modal-body">
        <?php //var_dump(get_class_methods($this)); ?>
        <?php echo $this->loginHelper(); ?>

    </div>
</div>