<?php
$output = '<nav class="navbar">';
$output .= '<div class="navbar-inner"><div class="container">';
$output .= ' <ul class="nav">';
foreach ($this->container as $page) {

    if ($page->class == 'right') {
        //if ($this->zfcUserIdentity()) {
        //    $output .= '</li></ul>';
        //    $output .= $this->partial('partials/userwidget');
        //} else {
        $output .= '</li></ul>';
        $output .= '<ul class="nav pull-right">';
        foreach ($page as $p) {
            $output .='<li>';
            $output .= '<a href="#loginModal" role="button" data-toggle="modal">Войти</a>';
            $output .='</li>';
        }
        $output .='</ul>';
        //}
    } else {

        $output .= '<li>';

        //var_dump($page->label.'<i class="icon-file"></i>');die();
        $output .= '<a href="' . $page->getHref() . '" class="' . $page->getClass() . '" >';
        switch ($page->id) {
            case 'desk': {
                $output .= '<i class="icon-th-list"></i>';
                break;
            }
            case 'reply': {
                $output .= '<i class="icon-envelope"></i>';
                break;
            }
            case 'users': {
                $output .= '<i class="icon-user"></i>';
                break;
            }
            case 'news': {
                $output .= '<i class="icon-globe"></i>';
                break;
            }
        }
        $output .=$page->getLabel();
        $output .='</a>';
        $output .='</li>';
        $output .= '<li class="divider-vertical"></li>';
    }
}
$output .= '<form class="navbar-search pull-left">';
$output .= '<input type="text" placeholder="Поиск" class="search-query">';
$output .= '</form></li></ul></div></div></nav>';

echo $output;
?>
<div id="loginModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Login to travelclub.com</h3>
    </div>
    <div class="modal-body">
        <?php echo $this->LoginHelper(); ?>

    </div>
</div>