<div class="sidebar-nav">
    <div style="width:200px; padding: 8px 0;margin-top:150px;" class="well">
        <ul class="nav nav-list">
            <li class="nav-header">Меню</li>
            <li class="active"><a href="index"><i class="icon-home"></i>Главная</a></li>
            <li><a href="#"><i class="icon-edit"></i> Добавить обьявление</a></li>
            <li><a href="#"><i class="icon-calendar"></i> Календарь</a></li>
            <li><a href="#"><i class="icon-user"></i> Пользователи</a></li>
            <li><a href="#"><i class="icon-comment"></i> Отклики</a></li>
            <li><a href="#"><i class="icon-picture"></i> Галерея</a></li>
        </ul>
    </div>
</div>