<div class="carousel slide" id="myCarousel">
    <div class="carousel-inner">
        <div class="item">
            <img alt="" src="img/slider/1.jpg">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Example headline.</h1>
                    <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <a href="#" class="btn btn-large btn-primary">Sign up today</a>
                </div>
            </div>
        </div>
        <div class="item active">
            <img alt="" src="img/slider/2.jpg">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <a href="#" class="btn btn-large btn-primary">Learn more</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img alt="" src="img/slider/3.jpg">
            <div class="container">
                <div class="carousel-caption">
                    <h1 style="color: white;">One more for good measure.</h1>
                    <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <a href="#" class="btn btn-large btn-primary">Browse gallery</a>
                </div>
            </div>
        </div>
    </div>
    <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a>
    <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a>
</div>