<!-- three blocs -->
<section class="sliceTop"> 

    <div class="container">

        <div class="row">

            <div class="span12 drop-shadow lifted">

                <div class="topQuote">
                    <h1>
                        Welcome to <strong>OHMy! Website Template</strong>, clean, HTML5 & CSS3, and Fully Responsive.<span> Build your website in no time!</span>
                    </h1>
                </div>
                <div class="topBox clearfix">
                    <div class="bigIconsColumnsWrapper">


                        <article class="one_third">

                            <a href="" class="iconWrapper iconBig ch-item">
                                <i class="icon-heart"></i>
                                <div class="ch-info">
                                    <span> more info </span>                                           
                                </div>
                            </a>

                            <h2 class="smallHeading"><span>Oh my God, </span> We love you</h2>
                            <p>We love creating professional templates that make you think "Oh my God! i love Little Neko!".</p>                       

                        </article>

                        <article class="one_third">

                            <a href="" class="iconWrapper iconBig ch-item">
                                <i class="icon-users"></i>
                                <div class="ch-info">
                                    <span> more info </span>                                           
                                </div>
                            </a>



                            <h2 class="smallHeading">We work for you</h2>
                            <p>We pay special attention to customization options so you can easily make this template your own.</p>                     

                        </article>

                        <article class="one_third last">


                            <a href="" class="iconWrapper iconBig ch-item">
                                <i class="icon-ok"></i>
                                <div class="ch-info">
                                    <span> more info </span>                                           
                                </div>
                            </a>


                            <h2 class="smallHeading">We are good at to-do lists</h2>
                            <p>We are always looking to improve and support, listening to user feedback to build even better stuff.</p>                   

                        </article>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 