<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Module.php',
    'Application\Controller\AbstractController' => __DIR__ . '/src/Application/Controller/AbstractController.php',
    'Application\Controller\ErrorController'    => __DIR__ . '/src/Application/Controller/ErrorController.php',
    'Application\Controller\IndexController'    => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\NewsController'     => __DIR__ . '/src/Application/Controller/NewsController.php',
    'Application\Controller\UploadController'   => __DIR__ . '/src/Application/Controller/UploadController.php',
    'Application\Controller\UserController'     => __DIR__ . '/src/Application/Controller/UserController.php',
    'Application\Form\Upload\ImageUploadForm'   => __DIR__ . '/src/Application/Form/Upload/ImageUploadForm.php',
);
