<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/error/access'   => __DIR__ . '/view/application/error/access.phtml',
    'application/error/index'    => __DIR__ . '/view/application/error/index.phtml',
    'application/index/index'    => __DIR__ . '/view/application/index/index.phtml',
    'application/news/index'     => __DIR__ . '/view/application/news/index.phtml',
    'application/test/index'     => __DIR__ . '/view/application/test/index.phtml',
    'application/upload/index'   => __DIR__ . '/view/application/upload/index.phtml',
    'application/upload/success' => __DIR__ . '/view/application/upload/success.phtml',
    'application/upload/upload'  => __DIR__ . '/view/application/upload/upload.phtml',
    'application/user/index'     => __DIR__ . '/view/application/user/index.phtml',
    'error/404'                  => __DIR__ . '/view/error/404.phtml',
    'error/index'                => __DIR__ . '/view/error/index.phtml',
    'layout/layout'              => __DIR__ . '/view/layout/layout.phtml',
    'partials/breadcrumbs'       => __DIR__ . '/view/partials/breadcrumbs.phtml',
    'partials/footer'            => __DIR__ . '/view/partials/footer.phtml',
    'partials/header'            => __DIR__ . '/view/partials/header.phtml',
    'partials/headerTopInfo'     => __DIR__ . '/view/partials/headerTopInfo.phtml',
    'partials/mainMenu'          => __DIR__ . '/view/partials/mainMenu.phtml',
    'partials/sideMenu'          => __DIR__ . '/view/partials/sideMenu.phtml',
    'partials/slider'            => __DIR__ . '/view/partials/slider.phtml',
    'partials/userwidget'        => __DIR__ . '/view/partials/userwidget.phtml',
);
