<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>

        <?php echo $this->headLink(); ?>
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->    
        <style type="text/css">

            /* Sticky footer styles
            -------------------------------------------------- */

          
            
        </style>
    </head>
    <body>

        <?php echo $this->partial('/partials/mainMenu') ?>                            
        <!--//header-->    
        <!-- Part 1: Wrap all page content here -->
        <div id="wrap">

            <!-- Begin page content -->
            <div class="container">

                <div class="page-header">
                    <h1>Travel club</h1>
                </div>
                <?php echo $this->partial('/partials/slider') ?>
                <?php //echo $this->partial('/partials/sideMenu') ?>                            
                <!--page_container-->
                <?php echo $this->content; ?>
                <!--//page_container-->
            </div>

            <div id="push"></div>
        </div>



        <!--footer-->
        <?php echo $this->partial('/partials/footer',array('title'=>'Travel club')) ?>
        <!--//footer-->    
        <?php
        echo $this->headScript();
        ?>

        <script type="text/javascript">

        </script>
    </body>
</html>

