<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>

        <?php echo $this->headLink(); ?>
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->    
        <style type="text/css">

            /* Sticky footer styles
            -------------------------------------------------- */

            html,
            body {
                height: 100%;
                /* The html and body elements cannot have any padding or margin. */
            }

            /* Wrapper for page content to push down footer */
            #wrap {
                min-height: 100%;
                height: auto !important;
                height: 100%;
                /* Negative indent footer by it's height */
                margin: 0 auto -60px;
            }

            /* Set the fixed height of the footer here */
            #push,
            #footer {
                height: 60px;
            }
            #footer {
                background-color: #f5f5f5;
            }

            /* Lastly, apply responsive CSS fixes as necessary */
            @media (max-width: 767px) {
                #footer {
                    margin-left: -20px;
                    margin-right: -20px;
                    padding-left: 20px;
                    padding-right: 20px;
                }
            }



            /* Custom page CSS
            -------------------------------------------------- */
            /* Not required for template or sticky footer method. */

            .container {
                width: 70%;

            }
         

        </style>
    </head>
    <body>

        <?php echo $this->partial('/partials/main_menu') ?>                            
        <!--//header-->    
        <!-- Part 1: Wrap all page content here -->
        <div id="wrap">

            <!-- Begin page content -->
            <div class="container">

                <div class="page-header">
                    <h1>Travel club</h1>
                </div>
                <?php echo $this->partial('/partials/slider') ?>

                <!--page_container-->
                <?php echo $this->content; ?>
                <!--//page_container-->
            </div>

            <div id="push"></div>
        </div>




        <!--footer-->
        <?php echo $this->partial('/partials/footer') ?>
        <!--//footer-->    
        <?php
        echo $this->headScript();
        ?>

        <script type="text/javascript">

        </script>
    </body>
</html>

