<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        
         <?php echo $this->headLink(); ?>
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->    
    </head>
    <body>
	
        <!--header-->
        <div class="header">
            <div class="wrap">
                <div class="navbar navbar_ clearfix">
                    <div class="container">
                        <div class="row">
                            <div class="span4">
                                <div class="logo"><a href="index.html"><img src="img/logo.png" alt="" /></a></div>                        
                            </div>
                            <div class="span8">
                                <div class="follow_us">
                                    <ul>
                                        <li><a href="#" class="facebook">Facebook</a></li>
                                        <li><a href="#" class="vimeo">Vimeo</a></li>
                                        <li><a href="#" class="tumbrl">Tumbrl</a></li>
                                        <li><a href="#" class="twitter">Twitter</a></li>
                                        <li><a href="#" class="delicious">Delicious</a></li>
                                    </ul>
                                </div>
                                <div class="clear"></div>
                                <?php echo $this->partial('/partials/main_menu') ?>                            
                            </div>
                        </div>                
                    </div>
                </div>
            </div>    
        </div>
        <!--//header-->    

        <!--page_container-->
			<?php echo $this->content; ?>
        <!--//page_container-->

        <!--footer-->
        <?php echo $this->partial('/partials/footer') ?>
        <!--//footer-->    
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->appendFile($this->basePath() . '//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js')
                                      ->appendFile($this->basePath() . '/js/jquery.easing.1.3.js')
                                      ->appendFile($this->basePath() . '/js/jquery.mobile.customized.min.js')
                                      ->appendFile($this->basePath() . '/js/camera.js')
                                      ->appendFile($this->basePath() . '/js/superfish.js')
                                      ->appendFile($this->basePath() . '/js/jquery.prettyPhoto.js')
                                      ->appendFile($this->basePath() . '/js/jquery.jcarousel.js')
                                      ->appendFile($this->basePath() . '/js/jquery.tweet.js')
                                      ->appendFile($this->basePath() . '/js/myscript.js')
                                      ->appendFile($this->basePath() . '/js/bootstrap.min.js'); ?>

        <script type="text/javascript">
                                        $(document).ready(function() {
                                            //Slider
                                            $('#camera_wrap_1').camera();

                                            //Featured works & latest posts
                                            $('#mycarousel, #mycarousel2, #newscarousel').jcarousel();
                                        });
        </script>
    </body>
</html>

