<?php
$form = $this->form;
$form->setAttribute('action', $this->url('caUser', array('action' => 'changepassword')));
$form->prepare();

echo "<div style='text-align:right; width:400px;'>" . $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('oldpassword'));
echo $this->formRow($form->get('newpassword'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag()."</div>";