<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    '/ca-user/user/cabinet'         => __DIR__ . '/view/ca-user/user/cabinet.phtml',
    '/ca-user/user/changepassword'  => __DIR__ . '/view/ca-user/user/changepassword.phtml',
    '/ca-user/user/exit'            => __DIR__ . '/view/ca-user/user/exit.phtml',
    '/ca-user/user/login'           => __DIR__ . '/view/ca-user/user/login.phtml',
    '/ca-user/user/registration'    => __DIR__ . '/view/ca-user/user/registration.phtml',
    '/ca-user/user/restorepassword' => __DIR__ . '/view/ca-user/user/restorepassword.phtml',
);
