<!-- Teaser -->
<div class="teaser">
    <div class="row-fluid">
        <div class="span4">
            <div class="item">
                <a target="_blank" href="#">
                    <figure>
                        <img alt="" src="http://3.s3.envato.com/files/17300140/IMG_3297.jpg">
                        <div class="overlay">
                            <i class="icon-star"></i>
                        </div>
                    </figure>
                    <article>
                        <h5>Lorem ipsum dolor sit amet.</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil adipisci.</p>
                    </article>
                </a>
            </div>
        </div>
    
    </div>
<!-- End Teaser -->
</div>
